language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data

script:
  - mkdir -p cmake-build-debug
  - cd cmake-build-debug
  - cmake ..
  - cmake --build .