version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=On -Dgtest_force_shared_crt=On -G "Visual Studio 15 2017 Win64"

build:
  project: $(APPVEYOR_BUILD_FOLDER)/build/$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%/build/%CONFIGURATION%/%APPVEYOR_PROJECT_NAME%Test.exe'
